version: "3.8"
services:
  soap-client:
    image: soap-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    command: "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
#    depends_on:
#      - redis-kv
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
      - JOB_PACKAGE_NAME=oracle/apps/ess/custom/Conversion/
      - JOB_DEFINITION_NAME=BHSGLTBREP
      - LAKE_CONTAINER_NAME=enterprisedata
      - LAKE_FOLDER_PATH=Raw/BOX Reports
    volumes:
      - ./jupyter:/opt/soap_service/local
