version: "3"
services:
  # Uses gunicorn for HTTP
  flask-ex:
    image: flask-ex
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - 5000:5000
#    expose:
#      - 5000
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development  # production
#      - FLASK_DEBUG=1
      - APP_SECRET=
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SQLALCHEMY_DEBUG=True
      - DB_DRIVER={ODBC Driver 17 for SQL Server}
      - DB_SERVER=
      - DB=
      - DB_USER=
      - DB_PWD=
  # Reverse proxy - minimal config
#  nginx:
#    image: nginx
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    ports:
#      - 8080:80
#    depends_on:
#      - flask-ex